name: test

on:
  push: {}

env:
    TARGET_DIR: master
    BUILDCACHE: /buildcache
    OS_VERSION: centos6
    MFMODULE: MFEXT
    MFMODULE_LOWERCASE: mfext
    MFBUILD: mfxxx
    DOCKER_RUN_OPTIONS: "-v ${{ github.workspace }}:/src -v /buildcache:/buildcache -v /private:/private -v /pub:/pub -e GITHUB_REF -e MFMODULE_LOWERCASE -e GITHUB_RUN_NUMBER -e GITHUB_SHA -e GITHUB_REPOSITORY -e TARGET_DIR -e BUILDCACHE -e OS_VERSION"
    WORKFLOW_SCRIPTS_DIR: .github/workflows
    DOCKER_WORKFLOW_SCRIPTS_DIR: /src/.github/workflows

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set variables
        id: SetVariables
        run: |
          ${WORKFLOW_SCRIPTS_DIR}/set_variables.sh
      - name: debug env
        run: |
          env
      - name: bootstrap
        run: |
          BUILDIMAGE=${{ steps.SetVariables.outputs.buildimage }}
          docker run ${DOCKER_RUN_OPTIONS} --rm ${BUILDIMAGE} /bin/bash -c "${DOCKER_WORKFLOW_SCRIPTS_DIR}/bootstrap.sh"
      - name: build
        run: |
          BUILDIMAGE=${{ steps.SetVariables.outputs.buildimage }}
          REF_BRANCH=${{ steps.SetVariables.outputs.refbranch }}
          docker run ${DOCKER_RUN_OPTIONS} -e BRANCH=${REF_BRANCH} --rm ${BUILDIMAGE} /bin/bash -c "${DOCKER_WORKFLOW_SCRIPTS_DIR}/build.sh"
      - name: buildlog publish 1
        uses: appleboy/ssh-action@master
        env:
          DIR: ${{ steps.SetVariables.outputs.buildlog_dir }}
        with:
          host: ${{ secrets.PUB_HOST }}
          username: ${{ secrets.PUB_USERNAME }}
          password: ${{ secrets.PUB_PASSWORD }}
          port: 22
          envs: DIR
          script: |
            mkdir -p ${DIR}
      - name: buildlog publish 2
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ${{ steps.SetVariables.outputs.buildlog_dir }}
          remote: ${{ steps.SetVariables.outputs.buildlog_dir }}
          host: ${{ secrets.PUB_HOST }}
          username: ${{ secrets.PUB_USERNAME }}
          password: ${{ secrets.PUB_PASSWORD }}
