name: test

on:
  push:
  pull_request:
  repository_dispatch:
    types: metwork-trigger

env:
    BUILDCACHE: /tmp/buildcache
    OS_VERSION: centos6
    MFMODULE: MFEXT
    MFMODULE_LOWERCASE: mfext
    MFBUILD: mfxxx
    DOCKER_RUN_OPTIONS: "-v ${{ github.workspace }}:/src -v /tmp/buildcache:/buildcache -v /private:/private -v /pub:/pub -e GITHUB_REF -e MFMODULE_LOWERCASE -e GITHUB_RUN_NUMBER -e GITHUB_SHA -e GITHUB_REPOSITORY -e TARGET_DIR -e BUILDCACHE -e OS_VERSION"
    WORKFLOW_SCRIPTS_DIR: .github/workflows
    DOCKER_WORKFLOW_SCRIPTS_DIR: /src/.github/workflows
    PAYLOAD_BRANCH: ${{ github.event.client_payload.branch}}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.client_payload.branch || github.ref }}
      - name: set variables
        id: SetVariables
        run: |
          ${WORKFLOW_SCRIPTS_DIR}/set_variables.sh
          git rev-list HEAD | wc -l
      - name: debug env
        run: |
          env
      - name: bootstrap
        run: |
          export TARGET_DIR=${{ steps.SetVariables.outputs.target_dir }}
          BUILDIMAGE=${{ steps.SetVariables.outputs.buildimage }}
          docker run ${DOCKER_RUN_OPTIONS} --rm ${BUILDIMAGE} /bin/bash -c "${DOCKER_WORKFLOW_SCRIPTS_DIR}/bootstrap.sh"
      - name: buildcache
        uses: actions/cache@v2
        env:
          cache-name: buildcache-${{ steps.SetVariables.outputs.repository }}-${{ steps.SetVariables.outputs.branch }}
        with:
          path: /tmp/buildcache
          key: ${{ env.cache-name }}-${{ hashFiles('*') }}
      - name: build
        run: |
          export TARGET_DIR=${{ steps.SetVariables.outputs.target_dir }}
          BRANCH=${{ steps.SetVariables.outputs.branch }}
          REF_BRANCH=${{ steps.SetVariables.outputs.ref_branch }}
          BUILDIMAGE=${{ steps.SetVariables.outputs.buildimage }}
          BUILDLOG_DIR=${{ steps.SetVariables.outputs.buildlog_dir }}
          docker run ${DOCKER_RUN_OPTIONS} -e BRANCH=${BRANCH} -e REF_BRANCH=${REF_BRANCH} -e BUILDLOG=${BUILDLOG_DIR} --rm ${BUILDIMAGE} /bin/bash -c "${DOCKER_WORKFLOW_SCRIPTS_DIR}/build.sh"
          ls -l ${BUILDCACHE}
      - name : check ssh connect as ssh-scp-ssh-pipelines does not do it
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PUB_HOST }}
          username: ${{ secrets.PUB_USERNAME }}
          password: ${{ secrets.PUB_PASSWORD }}
          port: 22
          script: |
            pwd
      - name: publish buildlogs
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        env:
          REMOTE: ${{ steps.SetVariables.outputs.buildlog_dir }}
          LOCAL: ${{ github.workspace }}/buildlogs
        with:
          host: ${{ secrets.PUB_HOST }}
          user: ${{ secrets.PUB_USERNAME }}
          pass: ${{ secrets.PUB_PASSWORD }}
          port: 22
          first_ssh: |
            mkdir -p ${REMOTE}
          scp: |
            '${LOCAL}/*' => ${REMOTE}
      - name: integration tests
        run: |
          TESTIMAGE=${{ steps.SetVariables.outputs.testimage }}
          REF_BRANCH=${{ steps.SetVariables.outputs.ref_branch }}
          docker run ${DOCKER_RUN_OPTIONS} -e REF_BRANCH=${REF_BRANCH} --rm ${TESTIMAGE} /bin/bash -c "${DOCKER_WORKFLOW_SCRIPTS_DIR}/integration_tests.sh"
      - name: publish rpms
        if: ${{ github.event_name == 'push' }}
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        env:
          REMOTE: ${{ steps.SetVariables.outputs.rpm_dir }}
          LOCAL: ${{ github.workspace }}/rpms
        with:
          host: ${{ secrets.PUB_HOST }}
          user: ${{ secrets.PUB_USERNAME }}
          pass: ${{ secrets.PUB_PASSWORD }}
          port: 22
          first_ssh: |
            mkdir -p ${REMOTE}
          scp: |
            '${LOCAL}/metwork-*.rpm' => ${REMOTE}
          last_ssh: |
            createrepo ${REMOTE} 
      - name: publish doc
        if: ${{ github.event_name == 'push' }}
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        env:
          REMOTE: ${{ steps.SetVariables.outputs.doc_dir }}
          LOCAL: ${{ github.workspace }}/html_doc
        with:
          host: ${{ secrets.PUB_HOST }}
          user: ${{ secrets.PUB_USERNAME }}
          pass: ${{ secrets.PUB_PASSWORD }}
          port: 22
          first_ssh: |
            rm -rf ${REMOTE}
            mkdir -p ${REMOTE}
          scp: |
            '${LOCAL}/*' => ${REMOTE}
